FROM python:3.6

RUN apt-get update

RUN mkdir /code

COPY . /code/

WORKDIR /code

COPY config/local.py.example config/local.py

RUN pip install -r requirements.txt

ARG BUILD="dev"
ARG BUILD="latest"
ARG DEBUG=False
ARG ALLOWED_HOSTS="[]"
ARG SITE_URL="http://localhost:8005/"
ARG WEBAPP_URL="http://localhost:8005/"
ARG APP_LOGO=""
ARG AWS_DEFAULT_REGION="us-east-2"
ARG JWT_SECRET_KEY=""
ARG DB_HOST=""
ARG DB_NAME=""
ARG DB_USER=""
ARG DB_PASS=""
ARG EMAIL_HOST=""
ARG EMAIL_HOST_USER=""
ARG EMAIL_HOST_PASSWORD=""
ARG EMAIL_PORT=""
ARG EMAIL_USE_TLS=""
ARG BASE_APP_DIR=""
ARG BLOCKING_TIME=1800
ARG INVALID_LOGIN_ATTEMPTS_COUNT=5
ARG CORS_ORIGIN_ALLOW_ALL=True

ENV BUILD=${BUILD}
ENV DEBUG=$DEBUG
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV SITE_URL=$SITE_URL
ENV WEBAPP_URL=${WEBAPP_URL}
ENV APP_LOGO=$APP_LOGO
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV EMAIL_HOST=$EMAIL_HOST
ENV EMAIL_HOST_USER=$EMAIL_HOST_USER
ENV EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
ENV EMAIL_PORT=$EMAIL_PORT
ENV EMAIL_USE_TLS=$EMAIL_USE_TLS
ENV BASE_APP_DIR=$BASE_APP_DIR
ENV BLOCKING_TIME=$BLOCKING_TIME
ENV INVALID_LOGIN_ATTEMPTS_COUNT=$INVALID_LOGIN_ATTEMPTS_COUNT
ENV CORS_ORIGIN_ALLOW_ALL=$CORS_ORIGIN_ALLOW_ALL

#RUN python manage.py collectstatic --noinput

#RUN python manage.py migrate

EXPOSE 8005

CMD ["python", "manage.py", "runserver", "0.0.0.0:8005"]
