# Generated by Django 2.0 on 2018-12-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20181207_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
