# Generated by Django 2.0 on 2018-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20181207_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='base_utc_offset',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='supports_day_light_saving_time',
            field=models.BooleanField(default=False),
        ),
    ]
