# Generated by Django 2.0 on 2018-12-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_auto_20181208_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
